title = "Terminal configuration"

[[config]]
title = "LF file manager"
file = "../config/lf.config"
winpath = "Local/lf/lfrc"
unixpath = "lf/lfrc"

[[config]]
title = "NeoVim text editor"
file = "../config/nvim.vim"
winpath = "Local/nvim/init.vim"
unixpath = "nvim/init.vim"

[[config]]
title = "Alacritty terminal emulator"
file = "../config/alacritty.yml"
winpath = "Roaming/alacritty/alacritty.yml"
unixpath = "alacritty.yml"

[[config]]
title = "Nu shell"
file = "../config/nu.toml"
winpath = "Roaming/nushell/nu/config/config.toml"
unixpath = "nu/config.toml"
