title = "Terminal configuration"

[[config]]
title = "NeoVim text editor"
file = "../config/nvim.vim"
winpath = "Local/nvim/init.vim"
unixpath = "nvim/init.vim"
darwinpath = "../../.config/nvim/init.vim"

[[config]]
title = "Starship prompt"
file = "../config/starship.toml"
darwinpath = "../../.config/starship.toml"

[[config]]
title = "Nu shell"
file = "../config/nu.toml"
winpath = "Roaming/nushell/nu/config/config.toml"
unixpath = "nu/config.toml"
