title = "VS Code configuration"

[[config]]
title = "Editor configuration"
file = "../config/vscode-config.json"
winpath = "Roaming/Code/User/settings.json"
unixpath = "Code/User/settings.json"

[[config]]
title = "Shortcut configuration"
file = "../config/vscode-keymap.json"
winpath = "Roaming/Code/User/keybindings.json"
unixpath = "Code/User/keybindings.json"

