title = "windows 10 configuration"
import = ["term.toml", "vscode.toml", "desktop.toml"]

[install]
scoop = ["rufus", "alacritty", "neovim", "scrcpy", "sqlite", "lf", "fzf", "deno"]
go = ["github.com/doronbehar/pistol@latest"]

[[install.url]]
url = "https://nmap.org/dist/nmap-7.91-win32.zip"
action = "unzip"
root = "nmap"

[install.cargo]
crate = ["bottom", "hyperfine"]
git = ["https://github.com/virgiel/ss", "https://github.com/Kethku/neovide"]
