shell = "sh -c '{}'"
default-theme = "base24-custom"

[[items]]
name = "tinted-terminal"
path = "https://github.com/tinted-theming/tinted-terminal"
themes-dir = "themes/ghostty"                                                                       # Directory name of terminal theme you want to use
hook = "mkdir -p ~/.config/ghostty/themes && cp -f %f ~/.config/ghostty/themes/tinted-theming.conf"
supported-systems = ["base16", "base24"]

[[items]]
name = "vscode"
path = "https://github.com/tinted-theming/tinted-vscode"
themes-dir = "themes/base24"
hook = "cp %f ~/.vscode/extensions/tintedtheming.base16-tinted-themes-*/themes/base24/base24-gruvbox-dark.json"
supported-systems = ["base16", "base24"]
