
palette = 0=#161616
palette = 1=#ea6962
palette = 2=#a9b665
palette = 3=#d8a657
palette = 4=#7daea3
palette = 5=#d3869b
palette = 6=#89b482
palette = 7=#e2cca9
palette = 8=#928374
palette = 9=#ef7e77
palette = 10=#b8c573
palette = 11=#e1b26a
palette = 12=#8ebaa4
palette = 13=#df97ac
palette = 14=#96c28e
palette = 15=#ede0cd

background = #121212
foreground = #e2cca9
cursor-color = #e78a4e
cursor-text = #e2cca9
selection-background = #32302f
selection-foreground = #e2cca9
  