
[colors]
background = "#161616"
foreground = "#e2cca9"
cursor = "#e78a4e"
black = "#e2cca9"
blue = "#7daea3"
cyan = "#89b482"
green = "#a9b665"
magenta = "#d3869b"
red = "#ea6962"
white = "#e2cca9"
yellow = "#d8a657"
dim-black = "#e2cca9"
dim-blue = "#68948a"
dim-cyan = "#4e664a"
dim-green = "#8f9a52"
dim-magenta = "#ab6c7d"
dim-red = "#b85651"
dim-white = "#e2cca9"
dim-yellow = "#c18f41"
light-black = "#e2cca9"
light-blue = "#8ebaa4"
light-cyan = "#96c28e"
light-green = "#b8c573"
light-magenta = "#df97ac"
light-red = "#ef7e77"
light-white = "#e2cca9"
light-yellow = "#e1b26a"
